# Generated by Django 4.1.7 on 2023-03-20 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='Date_Added',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='Product_Quantity',
            field=models.CharField(max_length=200),
        ),
    ]
