# Generated by Django 4.1.7 on 2023-03-20 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouse', '0005_alter_warehouse_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='Date_Added',
            field=models.DateTimeField(),
        ),
    ]
